package:
  name: ptsa
  version: 1.1.5

source:
  git_url: ../

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python {{ python }}
    - numpy
    - pip
    - pytables
    - setuptools
    - scipy
    - swig
    - xarray

  run:
    - python {{ python }}
    - h5py
    - numpy
    - pytables
    - scipy
    - vs2015_runtime  [win]
    - xarray
    - traits

test:
  # Test that we can import ptsa and its extension modules
  imports:
    - ptsa
    - ptsa.extensions.morlet
    - ptsa.extensions.circular_stat

about:
  home: https://github.com/pennmem/ptsa_new
  license: GPLv3
  license_file: LICENSE
