{% set setup_data = load_setup_py_data() %}

package:
  name: ptsa
  version: {{ setup_data.get('version') }}
  channels: anaconda pennmem

source:
  git_url: ../
  git_tag: staging

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python {{ python }}
    - numpy
    - pip
    - setuptools
    - scipy
    - swig
    - xarray
    - fftw
    - pybind11

  run:
    - python {{ python }}
    - h5py
    - fftw
    - numpy
    - scipy
    - vs2015_runtime  [win]
    - xarray
    - traits
    - pybind11

test:
  # Test that we can import ptsa and its extension modules
  imports:
    - ptsa
    - ptsa.extensions.morlet
    - ptsa.extensions.circular_stat

about:
  home: https://github.com/pennmem/ptsa_new
  license: GPLv3
  license_file: LICENSE
  summary: Python Time Series Analysis toolbox
