package:
  name: ptsa
  version: 3.0.3
  channels: anaconda pennmem

source:
  git_url: ../
  # git_tag: staging

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python {{ python }}
    - numpy >=1.17
    - pip
    - setuptools
    - scipy
    - swig>=4.1.0           # required for python>=3.9 
    - xarray
    - fftw
    - pybind11

  run:
    - python {{ python }}
    - h5py
    - fftw
    - numpy
    - scipy
    - vs2015_runtime  [win]
    - xarray
    - traits
    - pybind11

test:
  # Test that we can import ptsa and its extension modules
  imports:
    - ptsa
    - ptsa.extensions.morlet
    - ptsa.extensions.circular_stat

about:
  home: https://github.com/pennmem/ptsa
  license: GPLv3
  license_file: LICENSE
  summary: Python Time Series Analysis toolbox
